# Gmsh - Copyright (C) 1997-2018 C. Geuzaine, J.-F. Remacle
#
# See the LICENSE.txt file for license information. Please report all
# bugs and problems to the public mailing list <gmsh@onelab.info>.

variables:
  EXTRA_OPTION: ""

# ----------------------------------------------
# Continuous integration builds for all branches
# ----------------------------------------------

linux64_ci:
  image: onelab/ubuntu18.04
  script:
    - mkdir build
    - cd build
    - cmake ${EXTRA_OPTION} ..
    - make -j 4
    - ctest -j 4 --output-on-failure
  tags:
    - linux64
    - docker
  except:
    - tags

linux64_minimal_ci:
  image: onelab/ubuntu18.04
  script:
    - mkdir build
    - cd build
    - cmake -DDEFAULT=0 ${EXTRA_OPTION} ..
    - make -j 4
    - cmake -DENABLE_PARSER=1 ..
    - make -j 4
    - cmake -DENABLE_POST=1 ..
    - make -j 4
    - cmake -DENABLE_MESH=1 ..
    - make -j 4
  tags:
    - linux64
    - docker
  except:
    - tags

linux64_cxx98_compat_ci:
  image: onelab/ubuntu16.04
  script:
    - mkdir build
    - cd build
    - export CXXFLAGS=-std=c++98
    - cmake -DENABLE_CXX11=0 -DENABLE_OCC=0 ${EXTRA_OPTION} ..
    - make -j 4
  tags:
    - linux64
    - docker
  except:
    - tags

windows64_ci:
  script:
    - md build
    - cd build
    - bash -c "/usr/bin/cmake -DCMAKE_PREFIX_PATH='/usr/local/opencascade;/usr/local;/usr/x86_64-w64-mingw32/sys-root/mingw' -DCMAKE_C_COMPILER=/usr/bin/x86_64-w64-mingw32-gcc.exe -DCMAKE_CXX_COMPILER=/usr/bin/x86_64-w64-mingw32-g++.exe -DCMAKE_Fortran_COMPILER=/usr/bin/x86_64-w64-mingw32-gfortran.exe -DCMAKE_RC_COMPILER=/usr/bin/x86_64-w64-mingw32-windres.exe -DPETSC_ARCH=complex_mumps_seq -DPETSC_DIR=/home/Administrateur/petsc -DSLEPC_DIR=/home/Administrateur/slepc -DENABLE_OS_SPECIFIC_INSTALL=1 ${EXTRA_OPTION} .."
    - bash -c "/usr/bin/make -j 8"
    - bash -c "ctest -j 4 --output-on-failure"
  tags:
    - windows64
    - shared
  except:
    - tags

windows64_msvc_ci:
  script:
    - md build
    - cd build
    - cmake -DENABLE_BLAS_LAPACK=0 -DENABLE_HXT=0 ${EXTRA_OPTION} ..
    - msbuild package.vcxproj
  tags:
    - windows64
    - shared
  except:
    - tags

# ------------------------------------------
# Official Linux builds (master branch only)
# ------------------------------------------

.linux_official: &linux_official
  only:
    - master@gmsh/gmsh
  script:
    - mkdir build
    - cd build
    - /usr/local/bin/cmake -DGMSH_HOST=gmsh.info -DCMAKE_PREFIX_PATH='/usr/local/opencascade;/usr/local' -DENABLE_NATIVE_FILE_CHOOSER:bool=FALSE -DPETSC_ARCH=complex_mumps_seq -DPETSC_DIR=/home/geuzaine/src/petsc -DSLEPC_DIR=/home/geuzaine/src/slepc ${EXTRA_OPTION} ..
    - make package -j 1
    - PKG=`ls gmsh-*.tar*`
    - scp -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa ${PKG} geuzaine@gmsh.info:.wwwgmsh/bin/Linux/${PKG/\.tar\.gz/\.tgz}
    - /usr/local/bin/ctest -D Experimental -j 1 --output-on-failure

linux64_official_snapshot:
  <<: *linux_official
  tags:
    - linux64
    - official
  except:
    - tags

linux64_official_release:
  variables:
    EXTRA_OPTION: "-DGMSH_RELEASE=1"
  <<: *linux_official
  tags:
    - linux64
    - official
  only:
    - /^gmsh_.*$/

linux64-sdk_official_snapshot:
  variables:
    EXTRA_OPTION: "-DENABLE_BUILD_DYNAMIC=1 -DINSTALL_SDK_README=1"
  <<: *linux_official
  tags:
    - linux64
    - official
  except:
    - tags

linux64-sdk_official_release:
  variables:
    EXTRA_OPTION: "-DGMSH_RELEASE=1 -DENABLE_BUILD_DYNAMIC=1 -DINSTALL_SDK_README=1"
  <<: *linux_official
  tags:
    - linux64
    - official
  only:
    - /^gmsh_.*$/

linux32_official_snapshot:
  <<: *linux_official
  tags:
    - linux32
    - official
  except:
    - tags

linux32_official_release:
  variables:
    EXTRA_OPTION: "-DGMSH_RELEASE=1"
  <<: *linux_official
  tags:
    - linux32
    - official
  only:
    - /^gmsh_.*$/

linux32-sdk_official_snapshot:
  variables:
    EXTRA_OPTION: "-DENABLE_BUILD_DYNAMIC=1 -DINSTALL_SDK_README=1"
  <<: *linux_official
  tags:
    - linux32
    - official
  except:
    - tags

linux32-sdk_official_release:
  variables:
    EXTRA_OPTION: "-DGMSH_RELEASE=1 -DENABLE_BUILD_DYNAMIC=1 -DINSTALL_SDK_README=1"
  <<: *linux_official
  tags:
    - linux32
    - official
  only:
    - /^gmsh_.*$/

# --------------------------------------------
# Official Windows builds (master branch only)
# --------------------------------------------

.windows_official: &windows_official
  only:
    - master@gmsh/gmsh
  script:
    - md build
    - cd build
    - bash -c "/usr/bin/cmake -DGMSH_HOST=gmsh.info -DCMAKE_PREFIX_PATH='/usr/local/opencascade;/usr/local;/usr/mingw32/sys-root/mingw' -DCMAKE_C_COMPILER=/usr/bin/mingw32-gcc.exe -DCMAKE_CXX_COMPILER=/usr/bin/mingw32-g++.exe -DCMAKE_Fortran_COMPILER=/usr/bin/mingw32-gfortran.exe -DCMAKE_RC_COMPILER=/usr/bin/mingw32-windres.exe -DPETSC_ARCH=complex_mumps_seq -DPETSC_DIR=/home/geuzaine/src/petsc -DSLEPC_DIR=/home/geuzaine/src/slepc -DENABLE_OS_SPECIFIC_INSTALL=1 ${EXTRA_OPTION} .."
    - bash -c "/usr/bin/make package -j 2"
    - bash -c "/usr/bin/scp -o StrictHostKeyChecking=no -i /home/geuzaine/.ssh/id_rsa gmsh-*.zip geuzaine@gmsh.info:.wwwgmsh/bin/Windows/"
    - bash -c "/usr/bin/ctest -D Experimental -j 2 --output-on-failure"

windows64_official_snapshot:
  <<: *windows_official
  tags:
    - windows64
    - official
  except:
    - tags

windows64_official_release:
  variables:
    EXTRA_OPTION: "-DGMSH_RELEASE=1"
  <<: *windows_official
  tags:
    - windows64
    - official
  only:
    - /^gmsh_.*$/

windows64-sdk_official_snapshot:
  variables:
    EXTRA_OPTION: "-DENABLE_OS_SPECIFIC_INSTALL=0 -DENABLE_BUILD_DYNAMIC=1 -DINSTALL_SDK_README=1"
  <<: *windows_official
  tags:
    - windows64
    - official
  except:
    - tags

windows64-sdk_official_release:
  variables:
    EXTRA_OPTION: "-DGMSH_RELEASE=1 -DENABLE_OS_SPECIFIC_INSTALL=0 -DENABLE_BUILD_DYNAMIC=1 -DINSTALL_SDK_README=1"
  <<: *windows_official
  tags:
    - windows64
    - official
  only:
    - /^gmsh_.*$/

windows32_official_snapshot:
  <<: *windows_official
  tags:
    - windows32
    - official
  except:
    - tags

windows32_official_release:
  variables:
    EXTRA_OPTION: "-DGMSH_RELEASE=1"
  <<: *windows_official
  tags:
    - windows32
    - official
  only:
    - /^gmsh_.*$/

windows32-sdk_official_snapshot:
  variables:
    EXTRA_OPTION: "-DENABLE_OS_SPECIFIC_INSTALL=0 -DENABLE_BUILD_DYNAMIC=1 -DINSTALL_SDK_README=1"
  <<: *windows_official
  tags:
    - windows32
    - official
  except:
    - tags

windows32-sdk_official_release:
  variables:
    EXTRA_OPTION: "-DGMSH_RELEASE=1 -DENABLE_OS_SPECIFIC_INSTALL=0 -DENABLE_BUILD_DYNAMIC=1 -DINSTALL_SDK_README=1"
  <<: *windows_official
  tags:
    - windows32
    - official
  only:
    - /^gmsh_.*$/

# ------------------------------------------
# Official MacOS builds (master branch only)
# ------------------------------------------

.macos_official: &macos_official
  only:
    - master@gmsh/gmsh
  script:
    - mkdir build
    - cd build
    - /usr/local/bin/cmake -DGMSH_HOST=gmsh.info -DCMAKE_PREFIX_PATH='/usr/local/opencascade;/usr/local' -DCMAKE_C_COMPILER=/opt/local/bin/clang-mp-3.9 -DCMAKE_CXX_COMPILER=/opt/local/bin/clang++-mp-3.9 -DENABLE_CAIRO=0 -DPETSC_ARCH=complex_mumps_seq -DPETSC_DIR=/Users/geuzaine/src/petsc -DSLEPC_DIR=/Users/geuzaine/src/slepc -DBLAS_LAPACK_LIBRARIES=/usr/local/lib/libopenblas.a -DENABLE_OS_SPECIFIC_INSTALL=1 ${EXTRA_OPTION} ..
    - make package -j 2
    - PKG=`ls gmsh-*.[dt][ma][gr]*`
    - if [[ $PKG == *".dmg"* ]]; then scp ${PKG} ace@ace36.montefiore.ulg.ac.be:/tmp; fi
    - if [[ $PKG == *".dmg"* ]]; then ssh ace@ace36.montefiore.ulg.ac.be /Users/ace/re-sign.sh /tmp/${PKG}; fi
    - if [[ $PKG == *".dmg"* ]]; then scp ace@ace36.montefiore.ulg.ac.be:/tmp/${PKG} .; fi
    - scp ${PKG} geuzaine@gmsh.info:.wwwgmsh/bin/MacOSX/${PKG/\.tar\.gz/\.tgz}
    - /usr/local/bin/ctest -D Experimental -j 2 --output-on-failure
  tags:
    - macos64
    - official

macos64_official_snapshot:
  <<: *macos_official
  except:
    - tags

macos64_official_release:
  variables:
    EXTRA_OPTION: "-DGMSH_RELEASE=1"
  <<: *macos_official
  only:
    - /^gmsh_.*$/

macos64-sdk_official_snapshot:
  variables:
    EXTRA_OPTION: "-DENABLE_OS_SPECIFIC_INSTALL=0 -DENABLE_BUILD_DYNAMIC=1 -DINSTALL_SDK_README=1"
  <<: *macos_official
  except:
    - tags

macos64-sdk_official_release:
  variables:
    EXTRA_OPTION: "-DGMSH_RELEASE=1 -DENABLE_OS_SPECIFIC_INSTALL=0 -DENABLE_BUILD_DYNAMIC=1 -DINSTALL_SDK_README=1"
  <<: *macos_official
  only:
    - /^gmsh_.*$/

# ----------------------------------------------
# Official source snapshots (master branch only)
# ----------------------------------------------

.source_official: &source_official
  only:
    - master@gmsh/gmsh
  script:
    - mkdir build_src
    - cd build_src
    - /usr/local/bin/cmake ${EXTRA_OPTION} ..
    - make package_source
    - PKG=`ls gmsh-*.tar*`
    - scp -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa ${PKG} geuzaine@gmsh.info:.wwwgmsh/src/${PKG/\.tar\.gz/\.tgz}
  tags:
    - linux64
    - official

source_official_snapshot:
  <<: *source_official
  except:
    - tags

source_official_release:
  variables:
    EXTRA_OPTION: "-DGMSH_RELEASE=1"
  <<: *source_official
  only:
    - /^gmsh_.*$/

# ----------------------------------------------
# Official documentation (master branch only)
# ----------------------------------------------

doc_official_snapshot:
  only:
    - master@gmsh/gmsh
  script:
    - mkdir build_doc
    - cd build_doc
    - /usr/local/bin/cmake ${EXTRA_OPTION} ..
    - make doc
    - scp -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa gmsh-*-doc.tgz geuzaine@gmsh.info:.wwwgmsh/doc.tgz
    - ssh -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa geuzaine@gmsh.info 'cd .wwwgmsh/dev && tar zxvf ../doc.tgz'
  tags:
    - linux64
    - official
  except:
    - tags

doc_official_release:
  variables:
    EXTRA_OPTION: "-DGMSH_RELEASE=1"
  only:
    - master@gmsh/gmsh
  script:
    - mkdir build_doc
    - cd build_doc
    - /usr/local/bin/cmake ${EXTRA_OPTION} ..
    - make doc
    - scp -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa gmsh-*-doc.tgz geuzaine@gmsh.info:.wwwgmsh/doc.tgz
    - ssh -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa geuzaine@gmsh.info 'cd .wwwgmsh && tar zxvf doc.tgz'
    - scp -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa ../doc/gmsh.html geuzaine@gmsh.info:.wwwgmsh/
  tags:
    - linux64
    - official
  only:
    - /^gmsh_.*$/
